name: Second Workflow

on:
  push:
    branches:
      - "update"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello from the second workflow!